### ISSUE TITLE
Upgrade TS to 2.2.1

### ISSUE THREAD

**Issue by kipz** [atomist/rug-typescript-compiler#15]
Also provide a class with a main method (with input/output paths as params) to compile TS stuff.

https://github.com/atomist/rug/issues/395

**Comment by Lawouach** [comment]
Related note, beware of this one https://github.com/Microsoft/TypeScript/issues/14351#issuecomment-282972698

I don't think they'll revert the change so we'll have to handle this.

**Comment by kipz** [comment]
https://github.com/Microsoft/TypeScript/pull/14493 might fix this

**Comment by Lawouach** [comment]
That'd be great. Though I don't know enough of that ecosystem to fully appreciate the impact of their change.

**Comment by kipz** [comment]
Yeah, I _think_ they've accepted that this is a bug. Otherwise, we'll need to polly fill it somehow :s

**Comment by kipz** [comment]
https://github.com/coveo/nashorn-commonjs-modules/pull/16 would fix this for us.
